#!/bin/bash
# ─────────────────────────────────────────────────────────────
# ynotPi — setup_keys.sh
# Walks you through entering your API keys one by one and saves
# them to config/secrets.env on the Pi. Safe, simple, no fuss.
# Usage: bash ~/ynotPi/scripts/setup_keys.sh
# ─────────────────────────────────────────────────────────────

INSTALL_DIR="$HOME/ynotPi"
SECRETS_FILE="$INSTALL_DIR/config/secrets.env"
EXAMPLE_FILE="$INSTALL_DIR/config/secrets.env.example"

echo ""
echo "========================================"
echo "  ynotPi — API Key Setup"
echo "========================================"
echo ""
echo "This will walk you through setting up your API keys."
echo "Keys are saved locally to: $SECRETS_FILE"
echo "That file is gitignored — it will never be uploaded to GitHub."
echo ""

# if secrets.env already exists, ask before overwriting
if [ -f "$SECRETS_FILE" ]; then
    echo "⚠️  A secrets.env file already exists."
    read -p "   Do you want to overwrite it? (y/n): " confirm
    echo ""
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        echo "Keeping existing secrets.env — nothing changed."
        exit 0
    fi
fi

# helper function — prompts for a key, shows a hint URL, accepts blank input
prompt_key() {
    local key_name="$1"
    local friendly_name="$2"
    local hint_url="$3"

    echo "──────────────────────────────────────"
    echo "  $friendly_name"
    if [ -n "$hint_url" ]; then
        echo "  Get your key at: $hint_url"
    fi
    echo "  (press Enter to skip for now)"
    read -p "  $key_name= " key_value
    echo ""

    # write key=value to the secrets file regardless of whether it's blank
    echo "$key_name=$key_value" >> "$SECRETS_FILE"
}

# start fresh — write the header to secrets.env
cat > "$SECRETS_FILE" << 'EOF'
# ─────────────────────────────────────────────────────────────
# ynotPi — secrets.env  (NEVER commit this file to GitHub!)
# Generated by scripts/setup_keys.sh
# ─────────────────────────────────────────────────────────────

EOF

echo "Enter your API keys below. Press Enter to skip any you don't have yet."
echo "You can re-run this script any time to update them."
echo ""

# ── prompt for each key ──

prompt_key "OPENWEATHER_API_KEY" \
    "OpenWeather — current weather & forecasts" \
    "https://openweathermap.org/api"

prompt_key "COINGECKO_API_KEY" \
    "CoinGecko — crypto prices (free tier works without a key)" \
    "https://www.coingecko.com/en/api"

prompt_key "NEWS_API_KEY" \
    "News API — top headlines from around the world" \
    "https://newsapi.org"

prompt_key "NASA_API_KEY" \
    "NASA — Astronomy Picture of the Day & more" \
    "https://api.nasa.gov"

prompt_key "SPOTIFY_CLIENT_ID" \
    "Spotify Client ID — currently playing track etc." \
    "https://developer.spotify.com/dashboard"

prompt_key "SPOTIFY_CLIENT_SECRET" \
    "Spotify Client Secret — goes with the Client ID above" \
    ""

# ── done ──
echo "========================================"
echo "  All done! Keys saved to:"
echo "  $SECRETS_FILE"
echo ""
echo "  To add more APIs later, just re-run:"
echo "  bash ~/ynotPi/scripts/setup_keys.sh"
echo "========================================"
echo ""
